import type { Metadata } from "next"
import type { ReactNode } from "react"

import "./globals.css"
import Header from "@/components/sections/header"

export const metadata: Metadata = {
  title: "GenColor",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang='en' className='dark'>
      <body className='antialiased'>
        <Header />
        {children}
      </body>
    </html>
  )
}
